#+TITLE:     cicada project
#+AUTHOR:    XIE Yuheng
#+EMAIL:     xyheme@gmail.com


* WARNING
  system is very unstable currently,
  please do NOT use it for something that requires stability.

* what is cicada ?
  cicada is a very simple programming language,
  it is a stack-based and functional language,
  the design of cicada is influenced by scheme and forth and joy.

* what is the purpose cicada project ?
  the purpose of the cicada project is <br/>
  to provide support                   <br/>
  about programming language and math  <br/>
  to programmable devices              <br/>
  for the creative spirit in everyone's mind ^_^

* what is state of this project currently ?
  - cicada for linux :: =other-operating-systems/linux/=
       which is currently under active development.
  - operating system for x86_64 :: =architecturals/x86-64/=
       which is currently under active development
  - [coming soon] operating system for ARM :: =architecturals/arm/=
       which will be running on raspberry pi.

* how to install and run ?
  please type =make help= or just =make=
  or read the Makefile.

* where can I find more documentations ?
  please visit
  http://cicada-language.github.io

* where to visit this open source project ?
  https://github.com/cicada-language

* how to contact you ?
  1. my name is XIE Yuheng
  2. my email address is =xyheme@gmail.com=
  3. email address of cicada language is =cicada.language@gmail.com=
  4. main IRC channel is =#cicada-language= at =irc.freenode.net=
